### ISSUE TITLE
Create an API construct

### ISSUE THREAD

**Issue by jayair** [serverless-stack/serverless-stack#22]
Make it easier to create APIs by creating a higher level construct. Need to automatically handle things like cold starts, etc.

### TODO
- [ ] easy way to enable CORS, if both cors and corsPreflight are defined, cors takes precedence
- [ ] enable access log by default, allow customizing log format
- [ ] enable xray by default for all lambdas
- [ ] enable AWS_NODEJS_CONNECTION_REUSE_ENABLED by default for all lambdas
- [ ] easy way to enable AWS_IAM authorization for all routes, allow override per route
- [ ] easy way to define common Lambda props (environment, policy, srcPath, etc) for all aroutes, allow override per route
