### ISSUE TITLE
Changing sst.Function construct take just 'handler' without 'entry'

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#38]
### Current definition
```
{ srcPath: 'src', entry: 'get.ts', handler: 'main' }
```

### New proposed definition
```
{ srcPath: 'src', handler: 'get.main' }
```

### TODO
- [ ] Update Function construct definition
- [ ] Update Function construct builder
- [ ] Update sst start builder
- [ ] Update templates
- [ ] Update sst start demo repo
- [ ] Update Function's doc
