### ISSUE TITLE
Create UserPool construct

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#458]
### Todo
- [ ] name the construct `UserPoolAuth`
- [ ] create UserPool internally with sane default
- [ ] create UserPoolClient with sane default
- [ ] easy way to create triggers with `defaultFunctionProps`

### Example
```js
new UserPoolAuth(this, "Auth", {
  cognitoUserPool: {
    // takes aws_cognito.UserPoolProps https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.UserPoolProps.html
  },
  cognitoUserPoolClient: {
    // takes aws_cognito.UserPoolClientOptions https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.UserPoolClientOptions.html
  },
  defaultFunctionProps: {
    timeout: 20,
    environment: { tableName: table.tableName },
    permissions: [table],
  },
  triggers: {
    preAuthentication: "src/preAuthentication.main",
    postAuthentication: "src/postAuthentication.main",
  },
});
```

---
_requested by Simon in Slack_

**Comment by fwang** [comment]
Added Auth construct.
