### ISSUE TITLE
Api: allow configure stage name

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#492]
By default, `sst.Api` creates the `$default` stage. We need to provide a way for ppl to use a custom stage name.
```js
new sst.Api(this, "Api", {
  customDomain: "api.sst.sh",
  stageName: scope.stage,
  routes: {
    "GET /": "src/lambda.main",
  },
});
```

### TODO
- [ ] set `createDefaultStage: false` on `this.httpApi`
- [ ] create a new stage:
  ```
    this.httpApi.addStage(props.stageName, {
      stageName: props.stageName,
      autoDeploy: true,
    });
  ```
- [ ] configure access log on the stage (currently only works for $default stage) 
- [ ] configure custom domain on the stage (currently only works for $default stage) 

---
Originally requested by:
- Ross Coundon in Slack, he prefers the API endpoint ends with the stage name
