### ISSUE TITLE
Allow custom path for stack definitions

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#553]
### TODO
- [x] add a `main` field to `sst.json` pointing to the index file (defaults to "lib/index.js")
- [x] add a test with custom `main` field. Similar to this test - https://github.com/serverless-stack/serverless-stack/tree/master/packages/cli/test/config
- [x] document the `main` field here - https://docs.serverless-stack.com/installation#project-config

**Comment by fwang** [comment]
Released in [v0.35.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.35.0)
