### ISSUE TITLE
Stack: allow configuring stack names not prefixed with `$stage-`

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#849]
## What's the problem
SST currently require stack names to be prefixed with the stage name, ie. `$stage-$appName-$stackId`. And ppl want to use a different format ie. `$stackId-$stage`.

## What's is the solution
We still want to make sure the stack name being parameterized with `$stage`. But doesn't have to be the prefix.

## Todo
- [ ] check if stack name starts with `$stage-`, ends with `-$stage` or includes `-$stage-`
- [ ] on synth, store a mapping of stack id to stack name on build
- [ ] on remove, if stack id is passed in, lookup the stack name from the mapping and remove the stack name.
